apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2024-10-13T14:32:25Z","generation":5,"labels":{"app":"sedai-kube"},"name":"sedai-kube","namespace":"monitoring","resourceVersion":"4684839","uid":"c4aad8e7-5fee-4185-95af-3de057b34907"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"sedai-kube"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"sedai-kube"}},"spec":{"containers":[{"image":"neergasm/sedai-k8s:0.1","imagePullPolicy":"IfNotPresent","name":"sedai-k8s","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2024-10-13T14:32:25Z","lastUpdateTime":"2024-10-13T14:32:34Z","message":"ReplicaSet \"sedai-kube-84fc6d976d\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2024-10-18T06:35:42Z","lastUpdateTime":"2024-10-18T06:35:42Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":5,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2024-10-22T10:16:43Z"
  generation: 1
  labels:
    app: sedai-kube
  name: sedai-kube
  namespace: monitoring
  resourceVersion: "8266514"
  uid: 61a27830-05a4-4701-b88e-6fd80dde85d2
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sedai-kube
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sedai-kube
    spec:
      containers:
      - image: neergasm/sedai-k8s:0.1
        imagePullPolicy: IfNotPresent
        name: sedai-k8s
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2024-10-22T10:16:45Z"
    lastUpdateTime: "2024-10-22T10:16:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-10-22T10:16:43Z"
    lastUpdateTime: "2024-10-22T10:16:45Z"
    message: ReplicaSet "sedai-kube-84fc6d976d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
